// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCeRpoaPuOJkz3omdnfY_QE_UEmWLipyRg',
//     appId: '1:199523766155:web:3e44c6e4aabcec76e5a98e',
//     messagingSenderId: '199523766155',
//     projectId: 'todoapproute-6a5bf',
//     authDomain: 'todoapproute-6a5bf.firebaseapp.com',
//     storageBucket: 'todoapproute-6a5bf.firebasestorage.app',
//     measurementId: 'G-MZYD5K23QZ',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBjIZz-3-n-VaUDMzSWuiJK--0XupkWO6o',
//     appId: '1:199523766155:android:75098a83a26f560ee5a98e',
//     messagingSenderId: '199523766155',
//     projectId: 'todoapproute-6a5bf',
//     storageBucket: 'todoapproute-6a5bf.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyB9gl9WUpA5vphfuliCmxS9hOYsSTqWm1Q',
//     appId: '1:199523766155:ios:d1aba66e11e0483de5a98e',
//     messagingSenderId: '199523766155',
//     projectId: 'todoapproute-6a5bf',
//     storageBucket: 'todoapproute-6a5bf.firebasestorage.app',
//     iosBundleId: 'com.example.toDo',
//   );
//
//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyB9gl9WUpA5vphfuliCmxS9hOYsSTqWm1Q',
//     appId: '1:199523766155:ios:d1aba66e11e0483de5a98e',
//     messagingSenderId: '199523766155',
//     projectId: 'todoapproute-6a5bf',
//     storageBucket: 'todoapproute-6a5bf.firebasestorage.app',
//     iosBundleId: 'com.example.toDo',
//   );
//
//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyCeRpoaPuOJkz3omdnfY_QE_UEmWLipyRg',
//     appId: '1:199523766155:web:665480081a5142e4e5a98e',
//     messagingSenderId: '199523766155',
//     projectId: 'todoapproute-6a5bf',
//     authDomain: 'todoapproute-6a5bf.firebaseapp.com',
//     storageBucket: 'todoapproute-6a5bf.firebasestorage.app',
//     measurementId: 'G-4E2F98Q5ZX',
//   );
// }